### ISSUE TITLE
Long Device Names

### ISSUE THREAD

**Issue by Akira-Hojo** [chironb/ChiCLI#1]
![image](https://user-images.githubusercontent.com/69775188/102544610-0db82f00-4083-11eb-8d4a-edc77b331460.png)

Devices with names over 22 characters long extend onto a new line. Recommend to simply truncate text after this length.

App has amazing potential! I think this thing could really shine with being in the extra auto boot rom slot as a replacement OS for the C128.

**Comment by chironb** [comment]
Thanks! Also, I appreciate the screenshot. I need to rework that section of code anyway, so I'll make sure to at the very least truncate the code. Thanks again!

**Comment by chironb** [comment]
This has been fixed.
