### ISSUE TITLE
Using VICE with CMDHD Support Cannot Change Directory on Different Partitions

### ISSUE THREAD

**Issue by paulhocker** [chironb/ChiCLI#3]
I am using VICE with the following setup

08 1541-2
09 CMDHD w/ 8 partitions
10 VICEFS

CHICLI is started from the first partition on 09

After starting, I am able to cd to TEST1 folder, however, using the PART command to change to Partition 8 (i) and then trying to change into directory OS results in no change.

See attached video for example.

https://user-images.githubusercontent.com/2214652/147835419-fcbd06f8-a31e-4def-8540-425f0f22c617.mp4

**Comment by chironb** [comment]
Thanks for the feedback - this is great! I haven't listed the CMDHD or VICEFS as being supported or tested with the latest version. I look into this and see if I can put support into the next version.

**Comment by chironb** [comment]
Is there any way you could include a sample disk image for me to test against?

**Comment by paulhocker** [comment]
[cmd.zip](https://github.com/chironb/ChiCLI/files/7803613/cmd.zip)

Here you go, let me know if you have any questions.

**Comment by chironb** [comment]
Oh thanks! But what I meant was a disk image. Like the equivalent of a D64 but for a CMD HD with partitions setup. I just want to be able to recreate your steps. Thanks!

**Comment by paulhocker** [comment]
When you unzip it, there should be a DHD file in it. This is viewable using DIRMaster. 

There is a bit of setup involved for CMD, so here are some steps to get your going.

1. Unzip the DOSCMDHD file and place in your DRIVES folder in VICE
2. Open VICE and add the ROM to the Machine > ROM > Drive ROMS section of SETTINGS
3. Create a new Drive and select CMD HD for drive type
4. Attached the DHD image to your device (you might need to reset)

Hope that helps, let me know if you need anything else.

[doscmdhd.zip](https://github.com/chironb/ChiCLI/files/7805238/doscmdhd.zip)

**Comment by chironb** [comment]
This should be fixed as of the 1.01 version.

**Comment by paulhocker** [comment]
Works perfectly! You have inspired me to do something similar for C128 that I have wanted to do for long time. Now -- when are you going to fix that problem with making directories on the 1581!?!

hahahaha -- just kidding 

take it easy and keep up the great inspiring work!

**Comment by chironb** [comment]
Thanks so much! 

FYI - ChiCLI works with and detects C128 systems running in C64 mode. 

Good luck with your project! 
- Chiron
