### ISSUE TITLE
US (NTSC) C64 detected as "Commodore 128D".

### ISSUE THREAD

**Issue by ZappedC64** [chironb/ChiCLI#4]
My NTSC C64 it reports that I have a "Commodore 128D". I took a picture and tried to include part of the C64. I started with the standard C64 ROM(v3). I have an ARMSid and a PLAster chip in my C64. The board in my C64 is a 250466. Please let me know if I can provide any additional information or if you need for me to run any tests
![us-ntsc-c64-detected-as-c128d](https://user-images.githubusercontent.com/28941677/147976750-417e8e28-3bc3-4056-b541-c185c52c0cb6.png)
.

**Comment by ZappedC64** [comment]
Results of the peek that you asked for on FB.

![image](https://user-images.githubusercontent.com/28941677/148128283-e63525cd-5396-4706-a4fd-fd011389fe91.png)

**Comment by ZappedC64** [comment]
OK, I tried with a bunch of other PLAs and even a real, working MOS PLA. ChiCLI still detects my C64 as a C128D.

**Comment by chironb** [comment]
Okay I've updated the model detection. I'll be posting the update soon.

**Comment by chironb** [comment]
This should be fixed as of the 1.01 version.

**Comment by chironb** [comment]
Would you mind re-testing this issue on your system? I found a problem with the old code and fixed it, and I tested it in VICE and on my own C128 (wedge), but it would be great if you could please test it as well. Thanks in advance!

**Comment by ZappedC64** [comment]
Still coming up as a C128D.  My C64 board is a 250466
![chicli-64as128d](https://user-images.githubusercontent.com/28941677/148847484-6505fedb-4779-487d-a5ff-82a4037a407f.png)
![c64-board-250466](https://user-images.githubusercontent.com/28941677/148847528-9bd19a9e-0ce9-4a6f-a84c-ca0ffe862208.png)
.

**Comment by chironb** [comment]
As per offline testing, we have resolved this issue.
