### ISSUE TITLE
Is "cd" supposed to work with sd2iec devices?

### ISSUE THREAD

**Issue by locodarwin** [chironb/ChiCLI#6]
Are "cd" and related commands supposed to work with sd2iec devices? If so, they currently do not. "cd" fails with "Er" on anything but the root. "mkdir" fails with a hang. It would be lovely if a user were able to browse in and out of folders on the file structure of an sd2iec device. Here's the operating environment:

- SX-64 with U2+ (U2 acting as REU only)
- sd2iec device as drive 8
- built in 1541 as drive 9
- JiffyDOS 6.1

If it's not supported and isn't going to be, that's fine. Just curious and interested.

**Comment by chironb** [comment]
I found this bug as well. I'll be uploading a fixed version within the next day.

**Comment by chironb** [comment]
I originally designed this to exactly those kinds of things and was motivated very much by my own SD2IEC. This bug is fixed and the update will address it.
